### ISSUE TITLE
cp: cannot stat '/app/*-template.yaml': No such file or directory 

### ISSUE THREAD

**Issue by ChinaRush** [IndustryEssentials/ymir-executor#35]
## My working directory 
![Screenshot from 2022-06-07 12-09-17](https://user-images.githubusercontent.com/39917677/172294464-c967a67a-90c2-4fc6-82ba-46c85bba2a20.png)

## app is in det-yolov5-tmi
![Screenshot from 2022-06-07 12-09-31](https://user-images.githubusercontent.com/39917677/172294625-2a06a814-d8d3-4c12-af55-22f3d632cdee.png)

## the building Dockerfile is in the same directory with det-yolov5-tmi
![Screenshot from 2022-06-07 12-15-22](https://user-images.githubusercontent.com/39917677/172294730-d5f87cdc-bdcd-4407-88cb-88818ca5c426.png)

***In ymir-executor : I run the command line : docker build -f Dockerfile . ：***
![Screenshot from 2022-06-07 12-17-30](https://user-images.githubusercontent.com/39917677/172295066-40b2cd07-06b8-48f0-891f-50a3c2a0a4fc.png)

***where app directory  should be placed properly?***

**Comment by yzbx** [comment]
> ## My working directory
> 
> ![Screenshot from 2022-06-07 12-09-17](https://user-images.githubusercontent.com/39917677/172294464-c967a67a-90c2-4fc6-82ba-46c85bba2a20.png)
> ## app is in det-yolov5-tmi
> 
> ![Screenshot from 2022-06-07 12-09-31](https://user-images.githubusercontent.com/39917677/172294625-2a06a814-d8d3-4c12-af55-22f3d632cdee.png)
> ## the building Dockerfile is in the same directory with det-yolov5-tmi
> 
> ![Screenshot from 2022-06-07 12-15-22](https://user-images.githubusercontent.com/39917677/172294730-d5f87cdc-bdcd-4407-88cb-88818ca5c426.png)
> 
> _**In ymir-executor : I run the command line : docker build -f Dockerfile . ：**_ ![Screenshot from 2022-06-07 12-17-30](https://user-images.githubusercontent.com/39917677/172295066-40b2cd07-06b8-48f0-891f-50a3c2a0a4fc.png)
> 
> _**where app directory should be placed properly?**_

the folder det-yolov5-tmi is not ready now (under code review). But you can use the dockerfile and code from [this repo](https://github.com/yzbx/ymir-executor/tree/copy-yolov5)

**Comment by ChinaRush** [comment]
I have rebuild the image from source code 
## My Document
![Screenshot from 2022-06-07 17-12-46](https://user-images.githubusercontent.com/39917677/172343573-61fac69f-207f-47bb-838d-fa29f695e317.png)

***but i get a file error like this***
![Screenshot from 2022-06-07 17-11-58](https://user-images.githubusercontent.com/39917677/172343765-785e32b9-7cea-4b25-8e85-d645a3513284.png)

**Comment by yzbx** [comment]
the det-yolov5-tmi will in pull request 17:00 today, we fixed the problem when convert ymir dataset to yolov5 dataset. (avoid copy image, load the ymir dataset directly)
