### ISSUE TITLE
det-yolov5-tmi构建镜像成功，但是无法通过ymir-gui导入。

### ISSUE THREAD

**Issue by wuyuanmm** [IndustryEssentials/ymir-executor#38]
请问，如何通过ymir-gui导入这些镜像，wuyuanmm1990/yolov5_docker这是我上传dockerhub的镜像，但是感觉似乎哪里有问题一直无法导入，而industryessentials/executor-det-yolov4-training 和industryessentials/executor-det-yolov4-mining可以很快的导入

**Comment by yzbx** [comment]
> 

你这个镜像不符合ymir的要求，请参考sample_executor：[ymir 用户自定义镜像制作指南](https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor)

或者参照这里的一些项目进行配置，主要有以下要求：
1. xxx-template.yaml 作为配置文件，用xxx表明镜像是训练/挖掘还是推理镜像。xxx 为 `{training, mining, infer}`中的一个。将xxx-template.yaml 复制到镜像中的/img-man中，参考[Dockerfile](https://github.com/IndustryEssentials/ymir/blob/master/docker_executor/sample_executor/Dockerfile) 
2. 安装ymir_exc，其功能类似sample_executor 中的executor文件夹，提供ymir参数及读写功能。
3. 启动程序及相应依赖，参考sample_executor中的`start.py`

**Comment by ChinaRush** [comment]
您好，我按照det-yolov5-tmi目录下的cuda111.dockerfile [构建的镜像](https://hub.docker.com/layers/231756793/buledocker/bova-yolov5-training/v1.0/images/sha256-2affe3a675f16e081ab783c1ee688e7a29139ef47923835ebed4e8b93ea7e4cd?context=repo) ，可以导入， 但是无法训练。

**Comment by ChinaRush** [comment]
> Traceback (most recent call last):
  File "/app/start.py", line 8, in <module>
    import cv2
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

这是ymir-executor-out.log报错，但是libgl1-mesa-glx包 dockerfile文件已经包含了，我通过container 重新安装了libgl1-mesa-glx，再更新镜像，也无法训练,一直卡着，查看ymir-executor-out.log文件，发现内容是空的。
![Screenshot from 2022-06-16 16-33-56](https://user-images.githubusercontent.com/39917677/174028912-f0220b9a-52ab-41ac-967c-81c5f295fe6b.png)

**Comment by yzbx** [comment]
> > Traceback (most recent call last):
> > File "/app/start.py", line 8, in 
> > import cv2
> > File "/usr/local/lib/python3.8/site-packages/cv2/**init**.py", line 181, in 
> > bootstrap()
> > File "/usr/local/lib/python3.8/site-packages/cv2/**init**.py", line 153, in bootstrap
> > native_module = importlib.import_module("cv2")
> > File "/usr/local/lib/python3.8/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > ImportError: libGL.so.1: cannot open shared object file: No such file or directory
> 
> 这是ymir-executor-out.log报错，但是libgl1-mesa-glx包 dockerfile文件已经包含了，我通过container 重新安装了libgl1-mesa-glx，再更新镜像，也无法训练,一直卡着，查看ymir-executor-out.log文件，发现内容是空的。 ![Screenshot from 2022-06-16 16-33-56](https://user-images.githubusercontent.com/39917677/174028912-f0220b9a-52ab-41ac-967c-81c5f295fe6b.png)

请确保我们使用的dockerfile是同一个，以cuda111.dockerfile为例，里面首先会执行
```
RUN	apt-get update && apt-get install -y gnupg2 git libglib2.0-0 \
    libgl1-mesa-glx curl wget zip \
```

这个我们已经测试过了，就是为了解决安装`import cv2`的问题。

**Comment by wuyuanmm** [comment]
以前的问题都解决了，但是最新更新的yolov5的代码，ymir_exc的dataset_reader没有items_count这个属性

**Comment by yzbx** [comment]
> items_count

[非常感谢你的反馈，我检查一下是不是没有发布到pypi, 库里面现在已经有了](https://github.com/IndustryEssentials/ymir/blob/dev/docker_executor/sample_executor/ymir_exc/ymir_exc/dataset_reader.py)

**Comment by wuyuanmm** [comment]
谢谢您的回复，我将关闭这个issue
