### ISSUE TITLE
使用阿里云构建yolov5镜像，报错

### ISSUE THREAD

**Issue by skytodmoon** [IndustryEssentials/ymir-executor#44]
![08 140) ADD sdet-yolovS-tml app](https://user-images.githubusercontent.com/11644650/174932139-767ecda9-893e-40e4-8bff-daefd70d88a8.png)
如上图所示，提示文件夹找不到。

**Comment by ChinaRush** [comment]
你是不是在det-yolov5-tmi目录下构建的， 要在ymir-executor 目录下build

**Comment by CatchBeliF-TAT** [comment]
> 你是不是在det-yolov5-tmi目录下构建的， 要在ymir-executor 目录下build

您好，在ymir-executor目录下好像也还是有这个问题，请问您是如何解决的？
![image](https://user-images.githubusercontent.com/88470384/175254540-45f650e8-0f20-4617-996f-016b9f410dc1.png)

**Comment by skytodmoon** [comment]
文件层级关系问题，我把dockerfile放到主目录下就可以了，阿里云容器构建镜像设置不支持当前的目录结构，本问题关闭。
