### ISSUE TITLE
训练有问题

### ISSUE THREAD

**Issue by ChinaRush** [IndustryEssentials/ymir-executor#45]
1.通过det-yolov5-tmi中的cuda111.dockerfile构建的yolov5镜像，训练一直在进行中，但tensorboard图是有的，
![Screenshot from 2022-06-22 14-52-10](https://user-images.githubusercontent.com/39917677/174964744-8a3b09ae-c5ed-4cb4-85ab-5eefd1826c56.png)
![Screenshot from 2022-06-22 14-52-31](https://user-images.githubusercontent.com/39917677/174964773-06fe3a21-a205-4972-b0e4-a2d00a1d29ef.png)

ymir-tensorboard-log 是正常训练了
![Screenshot from 2022-06-22 14-53-39](https://user-images.githubusercontent.com/39917677/174964803-dcb180ae-9633-4ab8-93cb-c2048e5a1a2b.png)
![Screenshot from 2022-06-22 15-05-23](https://user-images.githubusercontent.com/39917677/174965536-3d97aaf6-bb7a-4075-aadc-50921d944690.png)

同时，找不到生成的in文件夹，out文件夹下也无models, 找不到训练结果

**Comment by CatchBeliF-TAT** [comment]
您好，打扰一下，因为看YMIR平台前端页面目前只支持YOLOX，darknet, 想问下您这边加载了新的镜像，有对前后端做什么改进嘛，因为后端这块不熟悉，自己这里想做YOLOX相关的镜像，但是一直困惑该怎么和后端进行交互，想请教一下，打扰啦！

**Comment by ChinaRush** [comment]
并没有哈，这些不影响镜像功能，项目好像有前后端代码，你可以试着改改

**Comment by yzbx** [comment]
> 1.通过det-yolov5-tmi中的cuda111.dockerfile构建的yolov5镜像，训练一直在进行中，但tensorboard图是有的， ![Screenshot from 2022-06-22 14-52-10](https://user-images.githubusercontent.com/39917677/174964744-8a3b09ae-c5ed-4cb4-85ab-5eefd1826c56.png) ![Screenshot from 2022-06-22 14-52-31](https://user-images.githubusercontent.com/39917677/174964773-06fe3a21-a205-4972-b0e4-a2d00a1d29ef.png)
> 
> ymir-tensorboard-log 是正常训练了 ![Screenshot from 2022-06-22 14-53-39](https://user-images.githubusercontent.com/39917677/174964803-dcb180ae-9633-4ab8-93cb-c2048e5a1a2b.png) ![Screenshot from 2022-06-22 15-05-23](https://user-images.githubusercontent.com/39917677/174965536-3d97aaf6-bb7a-4075-aadc-50921d944690.png)
> 
> 同时，找不到生成的in文件夹，out文件夹下也无models, 找不到训练结果

ymir 系统默认会自动删除/in目录，out目录下的文件也会清理。如果不希望清理，需要修改[ymir源码](https://github.com/IndustryEssentials/ymir/blob/master/ymir/command/mir/tools/command_run_in_out.py)，修改或注释其中的`_cleanup()`函数。

**Comment by yzbx** [comment]
> 您好，打扰一下，因为看YMIR平台前端页面目前只支持YOLOX，darknet, 想问下您这边加载了新的镜像，有对前后端做什么改进嘛，因为后端这块不熟悉，自己这里想做YOLOX相关的镜像，但是一直困惑该怎么和后端进行交互，想请教一下，打扰啦！

参考[ymir-executor的制作文档](https://github.com/IndustryEssentials/ymir/pull/763)

**Comment by ChinaRush** [comment]
好的，我仅仅修改了yolov5s.yaml文件的UpSample层，构建的镜像出现了这种问题，训练一直是0，所以也无法下载pt文件，但是从tensorboard来看，确实是训练成功了。而通过您的det-yolov5-tmi镜像训练，可以下载完整的训练结果。
