### ISSUE TITLE
用yolov5镜像训练出错

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/ymir-executor#46]
请问这是镜像没装好吗？
<img width="835" alt="image" src="https://user-images.githubusercontent.com/88470384/175338602-c813bb37-4b81-4691-9dd3-2f0a46d99ad9.png">
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/88470384/175338712-e27055a0-018f-43ef-a2ed-3e4496073a6c.png">

**Comment by yzbx** [comment]
> 请问这是镜像没装好吗？ <img alt="image" width="835" src="https://user-images.githubusercontent.com/88470384/175338602-c813bb37-4b81-4691-9dd3-2f0a46d99ad9.png"> <img alt="image" width="1075" src="https://user-images.githubusercontent.com/88470384/175338712-e27055a0-018f-43ef-a2ed-3e4496073a6c.png">

不是，这应该是ymir_exc的问题

下载ymir-exc的安装包
https://github.com/yzbx/ymir-executor-fork/releases/download/dataset/ymir-executor-executor.zip

将这个包解压，将其中的executor文件夹解压到当前目录，在dockerfile中将安装ymir-exc的部分替换为：
ADD executor /executor
RUN pip install -e /executor
