### ISSUE TITLE
用det-yolov5-tmi训练完后出结果时报错

### ISSUE THREAD

**Issue by zandb2009** [IndustryEssentials/ymir-executor#56]
用det-yolov5-tmi里的cuda111.dockerfile文件打的docker镜像，加入ymir进行训练，训练完后失败。
ymir-executor-out.log日志文件里报如下错误：
P@.5 mAP@.5:.95:  62%|██████▏   | 8/13 [00:00<00:00, 11.32it/s]^M               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  77%|███████▋  | 10/13 [00:00<00:00, 11.14it/s]^M               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  92%|█████████▏| 12/13 [00:01<00:00, 11.13it/s]^M               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 13/13 [00:01<00:00, 11.57it/s]
                 all        400       2031      0.794      0.514      0.626      0.295
Traceback (most recent call last):
  File "train.py", line 664, in <module>
    main(opt)
  File "train.py", line 560, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 421, in train
    write_ymir_training_result(ymir_cfg, map50=results[2], epoch=epoch, weight_file=weight_file)
  File "/app/utils/ymir_yolov5.py", line 221, in write_ymir_training_result
    rw.write_model_stage(stage_name=f"{model}_{epoch}",
AttributeError: module 'ymir_exc.result_writer' has no attribute 'write_model_stage'
Traceback (most recent call last):
  File "/app/start.py", line 133, in <module>
    sys.exit(start())
  File "/app/start.py", line 24, in start
    _run_training(cfg)
  File "/app/start.py", line 70, in _run_training
    subprocess.run(command.split(), check=True)
  File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'train.py', '--epochs', '300', '--batch-size', '16', '--data', '/out/data.yaml', '--project', '/out', '--cfg', 'models/yolov5s.yaml', '--name', 'models', '--weights', 'yolov5s.pt', '--img-size', '640', '--save-period', '10', '--exist-ok']' returned non-zero exit status 1.

**Comment by yzbx** [comment]
> 用det-yolov5-tmi里的cuda111.dockerfile文件打的docker镜像，加入ymir进行训练，训练完后失败。 ymir-executor-out.log日志文件里报如下错误： P@.5 mAP@.5:.95: 62%|██████▏ | 8/13 [00:00<00:00, 11.32it/s]^M Class Images Labels P R mAP@.5 mAP@.5:.95: 77%|███████▋ | 10/13 [00:00<00:00, 11.14it/s]^M Class Images Labels P R mAP@.5 mAP@.5:.95: 92%|█████████▏| 12/13 [00:01<00:00, 11.13it/s]^M Class Images Labels P R mAP@.5 mAP@.5:.95: 100%|██████████| 13/13 [00:01<00:00, 11.57it/s] all 400 2031 0.794 0.514 0.626 0.295 Traceback (most recent call last): File "train.py", line 664, in main(opt) File "train.py", line 560, in main train(opt.hyp, opt, device, callbacks) File "train.py", line 421, in train write_ymir_training_result(ymir_cfg, map50=results[2], epoch=epoch, weight_file=weight_file) File "/app/utils/ymir_yolov5.py", line 221, in write_ymir_training_result rw.write_model_stage(stage_name=f"{model}_{epoch}", AttributeError: module 'ymir_exc.result_writer' has no attribute 'write_model_stage' Traceback (most recent call last): File "/app/start.py", line 133, in sys.exit(start()) File "/app/start.py", line 24, in start _run_training(cfg) File "/app/start.py", line 70, in _run_training subprocess.run(command.split(), check=True) File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['python3', 'train.py', '--epochs', '300', '--batch-size', '16', '--data', '/out/data.yaml', '--project', '/out', '--cfg', 'models/yolov5s.yaml', '--name', 'models', '--weights', 'yolov5s.pt', '--img-size', '640', '--save-period', '10', '--exist-ok']' returned non-zero exit status 1.

- write_model_stage 是ymir下个版本的功能，需要用--build-arg SERVER_MODE=dev才能安装最新的ymir_exc
```
docker build -t ymir-executor/ymir1.2.0:cuda111-yolov5-tmi --build-arg SERVER_MODE=dev -f cuda111.dockerfile .
```

**Comment by zandb2009** [comment]
ymir1.2.0 这个版本还没发布吧？

**Comment by yzbx** [comment]
> ymir1.2.0 这个版本还没发布吧？



> ymir1.2.0 这个版本还没发布吧？

是的，我后续会考虑在dockerfile中添加ymir版本的参数，从而支持不同的版本。如果您有更好的建议，请及时告诉我们，感谢您的反馈。

**Comment by zandb2009** [comment]
好的，谢谢
